"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./header";
import { RoomProvider } from "./context/RoomContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RoomProvider>
      <html lang="en">
        <body className="bg-body">
          <Header />
          <div className="flex items-center justify-center w-full">{children}</div>
        </body>
      </html>
    </RoomProvider>
  );
}
